### ISSUE TITLE
java.lang.java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	

### ISSUE THREAD

**Issue by TanTai97o** [TanTai97o/skhstore.github.io#2]
```
java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.nazo.messenger.CreateImagePostActivity$ImagesViewAdapter$5.onClick(CreateImagePostActivity.java:503)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.widget.CompoundButton.performClick(CompoundButton.java:157)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by TanTai97o** [comment]
# 1

**Comment by TanTai97o** [comment]
#1
